### ISSUE TITLE
CoinOR upgrade

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/contrib#23]
I want to upgrade CoinOR (to 1.8.3) because of a bug compiling on newer OSX systems.
On Linux and OSX now everything works fine but i have a question regarding Windows:

I created new solutions based on the existent ones in the newest CoinMP release (usually v9, sometimes v10 available) like described in the CMake files.
However, it seems that CoinMP is the parent project of all of them and unfortunately it always tries to only override the v9 solutions of the subfolder. They seem to be hard-linked there.
If I refuse to upgrade the subproject solutions for v9, it still works but the subprojects are built via the v9 solution only.

Question: Is this bad or should this be no problem to build the subprojects for v9 and aggregate them in CoinMP with the e.g. v11 solution?
If it IS a problem: Can you suggest me how to upgrade such a hierarchical project on Windows such that all individual projects are upgraded?

I am hoping that e.g. @cbielow knows something about this.

**Comment by jpfeuffer** [comment]
Okay. I got part of it. The subprojects are found under References..
I could not edit them in the GUI but find/replaced with notepad++.
Still, if somebody knows something important about conversion, let me still know.

**Comment by cbielow** [comment]
creating VS-Sln's for hithero unsupported VS versions can be a real pain 
-- the worst thing that can happen is that it does not compile due to 
wrong includes in new toolchains etc.

But lets assume that's ok for now :)

The way I used to do goes like this (from memory):

- copy the complete build folder (here v9) and rename the copy 
accordingly (v11, or whatever VS version you want to port)
- rename all(!) other folders (v8,v9,v10 etc) or temporarily move them 
somewhere else. This ensures that when upgrading the solution, you do 
not inadvertedly upgrade a reference in v9 or so. Because if that would 
happen, the v9 folder becomes useless for VS9 (which you will not 
notice, since you are testing v11)!!!!
- do the upgrading -- this involves Notepad to correct the relative 
paths in the subprojects (I think within the .vcproj files or the 
.sln's.. or both.. not sure)
- make sure the Debug and Release targets are still named correctly and 
the lib type (static/dynamic) is still ok -- I think that sometimes got 
lost -- you will also notice this when building the contrib, but its 
better to check now.
- build the targets from within the VS IDE, and check for compile errors 
(as mentioned in the beginning)
- remove the .user(?) files which are created by VS (I think they are 
meant as a cache) -- not required but cleaner IMHO
- un-move the stashed other VS folders (v9,v10...)
- repackage the tar.gz.
- test contrib with different versions of VS -- in theory, you need to 
also link a corresponding version of OpenMS against it, and run TOPPView 
or alike, just to make sure that VS did use the correct compiler (it 
likes to switch toolchains in the background, even though you openend 
VS2013, it can use VS2012 toolchain (if installed) if configured 
incorrectly, i.e. you missed a reference). This might even compile and 
link, but might not execute... very nasty bug to have. You can spend 
days on this...

Hope this helps a little. Good luck :)

cheers
Chris

Am 7/13/2016 um 17:17 schrieb jpfeuffer:

**Comment by jpfeuffer** [comment]
Thanks a lot. I got a lot further. They build with VS 9-12.0 now. I still have to link them to see if the right toolchains were actually used.

**Comment by jpfeuffer** [comment]
@cbielow Concerning automatic tests, if the linking worked: What would you say is the minimum requirement for a build (that can be automatically tested) with GUI to be stable? This is related to the GUI test discussion we had some time ago.
