### ISSUE TITLE
Introduce tags and use in CI

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/contrib#32]
@jpfeuffer 
Currently, we don't track the corresponding OpenMS version. We should use tags and use them to check out the appropriate version in e.g. CI.  Otherwise changes to the contrib will break either the master or develop build in OpenMS/OpenMS. Also if one wants to build an older version he must look up the correct contrib version based on e.g. the date.

**Comment by jpfeuffer** [comment]
Yes I was thinking about this lately for the upcoming release.
After thinking about some options, I would kind of prefer to have a kind of reference to the used commit for both Thirdparty and contrib in the main OpenMS repository.
It could be done with git sub(module/tree/repo) which offers an easy way to also checkout the dependent repos when they are needed but I am not sure if we need the git history of these projects in the main repo.
Also for Thirdparty we only need a part of the repo dependent on which platform we are and actually need it in a different layout (e.g. Sirius has platform independent and dependent parts).
The problem with labels is that it's error prone and also not easy for CI to know when and to which commit a label was changed, and no CI build is triggered since it is actually not a change in the main repo.

**Comment by hroest** [comment]
git submodules could also simplify our quickbild.sh script, so I am all for it.

**Comment by jpfeuffer** [comment]
Done.
